version: '3.8'

services:
  flask:
    build:
      context: ./flask
    container_name: flask-service
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - /tmp/captures:/app/captures
    environment:
      #- FLASK_ENV=production
      - SWITCH_IP=10.112.0.2
      - SWITCH_USERNAME=opsmon
      - SWITCH_PASSWORD=0p@M0n*tor
  capture-ui:
    build:
      context: ./capture-ui-static
    container_name: capture-ui-static
    environment:
      - REACT_APP_API_HOST=otic-kvm-02.colosseum.net
    ports:
      - "80:80"
    volumes:
      - /tmp/captures:/usr/share/nginx/html/captures:ro
